# Generated by Django 5.0.14 on 2025-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=256)),
            ],
        ),
    ]
