# Generated by Django 5.0.14 on 2025-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_content',
            field=models.TextField(default=''),
        ),
    ]
